//
//  HomeInteractor.swift
//  GhostVPN
//
//  Created by Владислав on 30.11.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol VPNManagerProtocol {
    func connectToVPN(serverInfo: VPNServerInfo, completion: @escaping (Error?) -> Void)
    func disconnectFromVPN(completion: @escaping (Error?) -> Void)
}

protocol HomeBusinessLogic {
    func connectToVPN()
    func disconnectFromVPN()
}

protocol LocationService {
    func currentLocation() -> VPNServerInfo
}

protocol HomeDataStore {
    //var name: String { get set }
}

final class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var presenter: HomePresentationLogic?

    private let vpnManager: VPNManagerProtocol
    private let locationService: LocationService
    
    init(vpnManager: VPNManagerProtocol, locationService: LocationService) {
        self.vpnManager = vpnManager
        self.locationService = locationService
    }
    
    func connectToVPN() {
        let serverInfo = locationService.currentLocation()
        vpnManager.connectToVPN(serverInfo: serverInfo) { error in
            
        }
    }
    
    func disconnectFromVPN() {
        vpnManager.disconnectFromVPN { error in
            
        }
    }
    
}
